### ISSUE TITLE
Support for presenting in table view

### ISSUE THREAD

**Issue by 3lvis** [reednj/TDSemiModal#10]
Hi, 

First of all thanks for your control it's amazing. I've been trying to add it to a project inside a table view but it has a weird offset. Even when you scroll the modal scrolls with you. I'm attaching an screenshot.

**Sreenshot**
![Screeshot](https://dl.dropbox.com/u/63377498/Screenshot.png)

**Comment by reednj** [comment]
I suspect the view has the wrong parent, and that is what is causing this.
Try launching from the parent view (of the tableview) and see if that fixes
it.
