### ISSUE TITLE
dismissSemiModalViewController breaks KIF Tests

### ISSUE THREAD

**Issue by linusthe3rd** [reednj/TDSemiModal#12]
I am currently using KIF for automated UI testing. My app uses TDSemiModal for displaying a date picker.

However, when my KIF tests presents and removes a TDSemiModal, the KIF test hangs and eventually times out with a failure. Digging into the KIF code, I learned that KIF only tolerates animations that last for 0.5 seconds [1].

The problem is that when dismissing the semi modal view controller, the animation delay is set to 0.7 seconds [2]. To work around this issue, I added the following code to UIViewController+TDSemiModalExtension.m:

```
-(void) dismissSemiModalViewController:(TDSemiModalViewController*)vc {
    double animationDelay = 0.7;
    #if RUN_KIF_TESTS
        animationDelay = 0.3;
    #endif

        // ...
}
```

I have [opened an issue with KIF about modifying the animation delay](https://github.com/square/KIF/issues/158), but that does not solve the current problem for the dismissSemiModalViewController method. 

I believe that the best solution to this issue is for KIF to fix its code, and users of both codebases to adopt the workaround I noted above. However, adding the above code to the TDSemiModal code is trivial and harmless thanks to the RUN_KIF_TESTS flag.

[1] See [KIF / Classes / KIFTestStep.m:282](https://github.com/square/KIF/blob/master/Classes/KIFTestStep.m#L282)
[2] See [UIViewController+TDSemiModalExtension.m](https://github.com/reednj/TDSemiModal/blob/master/Source/UIViewController%2BTDSemiModalExtension.m#L39)

**Comment by reednj** [comment]
Well, I'm not that crazy about putting in changes to get around bugs in a framework I don't even use, but like you said, its a pretty trivial fix, so if you send me a pull request with a comment on the #if explaining the reason its there, I'll be happy to merge it in.
