### ISSUE TITLE
Adding Cover View and modal view on rootview controller distorts and places the picker view out of the window

### ISSUE THREAD

**Issue by kunalbalani** [reednj/TDSemiModal#13]
![Screen Shot 2013-01-14 at 10 35 05 AM](https://f.cloud.github.com/assets/2312637/64889/21521e30-5e60-11e2-9d97-14cef3f30d26.png)

Modal view and root view is placed on top of the rootview . In some application like mine where the root view moves sometimes outside the window . The picker view produces some weird results. 

```
UIWindow* mainWindow = [[UIApplication sharedApplication] keyWindow];
[mainWindow addSubview:coverView];
 [mainWindow addSubview:modalView];
```

adding that in - (void) presentSemiModalViewController:(TDSemiModalViewController*)vc ; 
Solves this problem because the modal view is always shown on top of the window.

**Comment by vbergae** [comment]
Included in https://github.com/vbergae/TDSemiModal/commit/ba92ce64e49fb36abb3bf7a8cdad8a88f10c06c1
