### ISSUE TITLE
TDDatePicker Locale

### ISSUE THREAD

**Issue by lucianoenrico** [reednj/TDSemiModal#14]
Hi,
   currently the date picker locale is set to US (in the TDDatePickerController.xib file). It must be more correct to use the current device locale.

It can be accomplished in the .xib file or setting to nil the locale property of the Date picker.

I think everyone will appreciate it.

Thank you

**Comment by stuffmc** [comment]
+1

**Comment by reednj** [comment]
I agree this should be done, but I don't really have the time at the moment
for it. But if someone sends me a pull request, I will merge it in

**Comment by stuffmc** [comment]
Hey @lucianoenrico — Here is how I use it, clearing the "Clear" button and using the current locale ;-)

``` objc
_datePickerController = [[TDDatePickerController alloc] initWithNibName:@"TDDatePickerController" bundle:nil];
_datePickerController.delegate = self;
[self presentSemiModalViewController:_datePickerController inView:self.navigationController.view];
_datePickerController.toolbar.items = @[_datePickerController.toolbar.items[0], _datePickerController.toolbar.items[1], _datePickerController.toolbar.items[3]];
_datePickerController.datePicker.datePickerMode = UIDatePickerModeTime;
_datePickerController.datePicker.date = myDate;
_datePickerController.datePicker.locale = [NSLocale currentLocale];
```

Given that last line, I think @reednj can close this Bug ;) You're welcome ;-) Not also I changed to a Time Picker.
