### ISSUE TITLE
Going background and entering app again causes coverview fade animation stop working

### ISSUE THREAD

**Issue by alejandroluengo** [reednj/TDSemiModal#17]
Just as title says, when you press home button and enter again on the app, when showing the controller coverview fade does not works, but only first time. if you launch it again then is ok. 

This happens both in real device and in simulator

;)

Regards,

**Comment by vbergae** [comment]
Hi @alejandroluengo,

I've checked this issue and works for me using iOS8. Could you check if the bug is still present in your scenario with latests version?

Thanks,
Víctor

**Comment by vbergae** [comment]
I'm going to close this issue until new information is provided
