### ISSUE TITLE
Fail to call presentSemiModalViewController again soon after click Cancel on the TDDatePicker

### ISSUE THREAD

**Issue by emptyway** [reednj/TDSemiModal#18]
Steps to reproduce the bug

Click on the UI which Activate
<code>[self presentSemiModalViewController:datePickerView];</code>

The normal TDPicker will show up

Click on cancel button which calls
<code>[self dismissSemiModalViewController:datePickerView];</code>

While the UI is dismissing(fading) quickly click on the UI which Activate the Picker again. the picker won't show if pressed before the fading process is completed

Note: I share the same Picker instance

**Comment by vbergae** [comment]
Hi @simonlinj 

Could you check if this bug is still present on version 1.0.0?

**Comment by vbergae** [comment]
I'm going to close this issue until new information is provided
