### ISSUE TITLE
Please add semantic version tags

### ISSUE THREAD

**Issue by philchristensen** [reednj/TDSemiModal#19]
I’ve recently added [TDSemiModal](https://github.com/philchristensen/Specs/tree/master/TDSemiModal) to the [CocoaPods](https://github.com/CocoaPods/CocoaPods) package manager repo.

CocoaPods is a tool for managing dependencies for OSX and iOS Xcode projects and provides a central repository for iOS/OSX libraries. This makes adding libraries to a project and updating them extremely easy and it will help users to resolve dependencies of the libraries they use.

However, TDSemiModal doesn't have any version tags. I’ve added the current HEAD as version 0.0.1, but a version tag will make dependency resolution much easier.

[Semantic version](http://semver.org) tags (instead of plain commit hashes/revisions) allow for [resolution of cross-dependencies](https://github.com/CocoaPods/Specs/wiki/Cross-dependencies-resolution-example).

In case you didn’t know this yet; you can tag the current HEAD as, for instance, version 1.0.0, like so:

```
$ git tag -a 1.0.0 -m "Tag release 1.0.0"
$ git push --tags
```

**Comment by vbergae** [comment]
Hi @philchristensen 

Now TDSemiModal follows semantic versions and version 1.0.0 is ready to be updated as pod. But I need that you grant me permission on trunk, so please can you run this command on your computer?

$ pod trunk add-owner TDSemiModal <hidden>

**Comment by philchristensen** [comment]
I don't understand, why would I need to do that? This isn't my project, I just made a fork for some reason.

-phil

**Comment by vbergae** [comment]
Yes, you're right, I apologize. I've re-readed the documentation and you don't need to do anything :)

@reednj FYI I'm currently the maintainer on CocoaPods, send me your email to add you as owner.

Tanks for your time guys,
Victor
