### ISSUE TITLE
How To create it for UIPickerView

### ISSUE THREAD

**Issue by bamlhs** [reednj/TDSemiModal#2]
Hello,

How can I use it for UIPickerView?

**Comment by bamlhs** [comment]
http://sms2day.ws/Archive.zip
please can you show me how Can I  send  didselect row with save botton?

**Comment by reednj** [comment]
You can use it with any type of view. If you look at the included example with the Date Picker you should be able to work out how to replace that with a generic picker. I'm not sure what you mean with the event, you will have to work that one out on your own.
