### ISSUE TITLE
Screenshot or animated gif?

### ISSUE THREAD

**Issue by andrewhavens** [reednj/TDSemiModal#23]
I just came across your library while trying to find a framework for implementing modals. However, I don't see a screenshot, animated gif, or video of what your library does. Can you please add a screenshot so that I can see if it will be something that I want to integrate?

**Comment by reednj** [comment]
Just google TDSemiModal, and there should be several screenshots. This blogpost is an example: http://www.alexcurylo.com/blog/2011/03/31/tdsemimodal/
