### ISSUE TITLE
codebase does not support ARC in iOS5

### ISSUE THREAD

**Issue by richarddas** [reednj/TDSemiModal#4]
When importing this to an ARC-enabled project, it throws errors. Perhaps worth branching to fix?

**Comment by reednj** [comment]
I haven't done any testing for this on iOS5, so I am not surprised that it
is throwing some errors. Any ideas on how much work it would take to get it
functioning correctly with ARC-enabled projects?

**Comment by klimchuk** [comment]
I don't think it's anyhow problem. You can disable ARC for certain files. Check http://www.leesilver.net/1/post/2011/8/disabling-arc-on-certain-files-in-xcode.html for more details.

**Comment by reednj** [comment]
Project has now been converted to ARC.
