### ISSUE TITLE
TDSemiModalViewController.m

### ISSUE THREAD

**Issue by lucianoenrico** [reednj/TDSemiModal#5]
in -(void)viewDidLoad

```
self.coverView = [[UIView alloc] initWithFrame:[UIScreen mainScreen].applicationFrame];
```

Static analyzer complains about a potential leak. It may be solved with:

```
self.coverView = [[[UIView alloc] initWithFrame:[UIScreen mainScreen].applicationFrame] autorelease];
```

in dealloc it must be like this? 

```
- (void)dealloc {
    //self.coverView = nil;
    [coverView release];
    [super dealloc];
}
```

**Comment by reednj** [comment]
The dealloc is ok, setting to nil on a retained property will release it. You are right that the initialisation is a memory leak. I have now converted the project to ARC, so this should no longer be a problem.
